# Generated by Django 3.2.12 on 2022-03-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_cadas_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadas',
            name='data_nascimento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cadas',
            name='genero',
            field=models.CharField(choices=[('', 'Escolha uma opção'), ('F', 'Feminino'), ('M', 'Masculino')], default='', max_length=1),
        ),
    ]
