# Generated by Django 3.2.12 on 2022-03-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20220330_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadas',
            name='softskills',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadas',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadas',
            name='leg_prog',
            field=models.BooleanField(blank=True, choices=[('py', 'Python'), ('Js', 'Javascript')], default='py'),
        ),
    ]
