# Generated by Django 3.2.12 on 2022-03-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20220330_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadas',
            name='leg_prog',
            field=models.CharField(blank=True, choices=[('', 'Python'), ('js', 'Javascript')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='cadas',
            name='softskills',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
